@apiUrlProd = http://rule-engine.runasp.net/v1
@apiUrlDev = http://localhost:5000/v1
@apiUrl = {{apiUrlDev}}

### Get All Rules
GET {{apiUrl}}/rules

### Evaluate Rule (LargeTransaction)
POST {{apiUrl}}/evaluate-rule
Content-Type: application/json

{
  "RuleName": "LargeTransactionRule",
  "RequestVariables": {
    "Amount": 15000,
    "Category": "Purchase"
  }
}

### Evaluate Rule (BulkOrderDiscount)
POST {{apiUrl}}/evaluate-rule
Content-Type: application/json

{
  "RuleName": "BulkOrderDiscountRule",
  "RequestVariables": {
    "ItemCount": 15
  }
}

### Evaluate Rule (BooleanCheck)
POST {{apiUrl}}/evaluate-rule
Content-Type: application/json

{
  "RuleName": "BooleanCheckRule",
  "RequestVariables": {
    "IsFlagEnabled": true
  }
}