### Get All Rules
GET http://localhost:5000/v1/rules

### Evaluate Rule (LargeTransactionRule)
POST http://localhost:5000/v1/evaluate-rule
Content-Type: application/json

{
  "RuleName": "LargeTransactionRule",
  "RequestVariables": {
    "Amount": 15000,
    "Category": "Purchase"
  }
}

### Evaluate Rule (BulkOrderDiscount)
POST http://localhost:5000/v1/evaluate-rule
Content-Type: application/json

{
  "RuleName": "BulkOrderDiscount",
  "RequestVariables": {
    "ItemCount": 15
  }
}